# Generated by Django 6.0.4 on 2026-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo de la promo')),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparicion')),
                ('activo', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, help_text='Opcional: link a una categoria o producto', null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
